[tool.poetry]
name = "issue-573"
version = "0.1.0"
description = "Reproduce pulumi-docker issue 573"
authors = ["expend"]

[tool.poetry.dependencies]
python = "^3.9"
pulumi = "^3.60"

[tool.poetry.group.dev.dependencies]
pulumi-docker = "^4.1.1"
pulumi-aws = "^5.34.0"
